### ISSUE TITLE
Does not work on VS Code Windows

### ISSUE THREAD

**Issue by daemon110282** [asyncapi/vs-asyncapi-preview#3]
Hello

I am try install latest version 0.0.1 from VS Code Extensions.
But not working when try preview: Command 'Preview AsyncAPI' resulted in an error (command 'asyncapi.preview' not found)

I am use sample yaml from https://playground.asyncapi.io/

**Comment by zabcik** [comment]
> Hello
> 
> I am try install latest version 0.0.1 from VS Code Extensions.
> But not working when try preview: Command 'Preview AsyncAPI' resulted in an error (command 'asyncapi.preview' not found)
> 
> I am use sample yaml from https://playground.asyncapi.io/

Hello,

my collague have same issue.
It seems that the activation event does not occur.

Why? Maybe YAML file is not detected and activationEvents is not triggered...?

Possible solution is update source code.
Fix "package.json", add "activationEvents" for command "asyncapi.preview" :

"activationEvents": [
    "onLanguage:yml",
    "onLanguage:yaml",
    "onCommand:asyncapi.preview"
  ],

**Comment by ivangsa** [comment]
Ok, version 0.1.0 works for me but I'm publishing version 0.1.1 with your suggestion

**Comment by zabcik** [comment]
Hello Iván,

issue still persists.

But it seems that issue is not in this extension.
I see error "Activating extension 'ivangsa.asyncapi-preview' failed: Cannot find module 'npm'." in "Help->Toggle Developer Tools->Console".

I tried to comment code fragments and detect whem issue stops.
Issue stop when I commented this line "const asyncapiGenerator = new AsyncAPIGenerator('@asyncapi/html-template', tmpdir()".
I checked AsyncAPIGenerator "@asyncapi/generator" documentation on web site https://github.com/asyncapi/generator

Documentation says that Generator requires installed these programs:
v12.16+ < Node.js
v6.13.7+ < npm

Please confirm, if is it possible, that user must have installed these programs before working with this extension?

If I am correct, then you should update README.md about these requirements.

BR
Tomas

**Comment by ivangsa** [comment]
@zabcik thanks for your help
I will update the README.md

**Comment by ceich** [comment]
Thanks, but can you update the extension's details page? Most folks don't go to the source repo when installing an extension.
